//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailInstallationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public long Id { get; set; }
        public string Barcode { get; set; }
        public string Process1_Data { get; set; }
        public string Process2_Data { get; set; }
        public string Process3_Data { get; set; }
        public string Process4_Data { get; set; }
        public string CompleteData { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsUploaded { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<System.DateTime> UploadedTime { get; set; }
    }
}
