//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailInstallationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadQueue
    {
        public long Id { get; set; }
        public string Barcode { get; set; }
        public string JsonData { get; set; }
        public Nullable<int> RetryCount { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastRetryTime { get; set; }
    }
}
